version: "3.9"

services:
  factory-ops-api:
    build:
      context: ./backend
    container_name: factory-ops-api
    image: factory-ops-api:0.3
    restart: always
    depends_on:
      - db
    ports:
      - 5005:8080
    volumes:
      - /var/wordpress/data:/var/www/html
    networks:
      - factoryOpsNetwork

  db:
    container_name: postgres
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}",]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      POSTGRES_DB: "factoryopsdb"
      POSTGRES_USER: "factoryops"
      POSTGRES_PASSWORD: "passwordinfile"
    volumes:
      - factory-ops-data:/var/lib/postgresql/data/
    networks:
      - factoryOpsNetwork

  factory-ops-frontend:
    build: 
      context: ./frontend/factory-ops
    container_name: factory-ops-frontend
    image: factory-ops-frontend:0.3
    restart: always
    ports:
      - 3000:3000
    networks:
      - factoryOpsNetwork

networks:
  factoryOpsNetwork:
    driver: bridge

volumes:
  factory-ops-data:


